package com.train.info.dao;

import com.train.info.pojo.StudentGrade;
import com.train.info.pojo.StudentGradeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
public interface StudentGradeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stu_grade
     *
     * @mbg.generated Wed Aug 05 13:14:42 CST 2020
     */
    long countByExample(StudentGradeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stu_grade
     *
     * @mbg.generated Wed Aug 05 13:14:42 CST 2020
     */
    int deleteByExample(StudentGradeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stu_grade
     *
     * @mbg.generated Wed Aug 05 13:14:42 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stu_grade
     *
     * @mbg.generated Wed Aug 05 13:14:42 CST 2020
     */
    int insert(StudentGrade record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stu_grade
     *
     * @mbg.generated Wed Aug 05 13:14:42 CST 2020
     */
    int insertSelective(StudentGrade record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stu_grade
     *
     * @mbg.generated Wed Aug 05 13:14:42 CST 2020
     */
    List<StudentGrade> selectByExample(StudentGradeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stu_grade
     *
     * @mbg.generated Wed Aug 05 13:14:42 CST 2020
     */
    StudentGrade selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stu_grade
     *
     * @mbg.generated Wed Aug 05 13:14:42 CST 2020
     */
    int updateByExampleSelective(@Param("record") StudentGrade record, @Param("example") StudentGradeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stu_grade
     *
     * @mbg.generated Wed Aug 05 13:14:42 CST 2020
     */
    int updateByExample(@Param("record") StudentGrade record, @Param("example") StudentGradeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stu_grade
     *
     * @mbg.generated Wed Aug 05 13:14:42 CST 2020
     */
    int updateByPrimaryKeySelective(StudentGrade record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table stu_grade
     *
     * @mbg.generated Wed Aug 05 13:14:42 CST 2020
     */
    int updateByPrimaryKey(StudentGrade record);
}