package com.train.info.pojo;

public class StudentGrade {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stu_grade.id
     *
     * @mbg.generated Wed Aug 05 13:14:42 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stu_grade.name
     *
     * @mbg.generated Wed Aug 05 13:14:42 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stu_grade.chinese
     *
     * @mbg.generated Wed Aug 05 13:14:42 CST 2020
     */
    private Integer chinese;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stu_grade.math
     *
     * @mbg.generated Wed Aug 05 13:14:42 CST 2020
     */
    private Integer math;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stu_grade.english
     *
     * @mbg.generated Wed Aug 05 13:14:42 CST 2020
     */
    private Integer english;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stu_grade.grade
     *
     * @mbg.generated Wed Aug 05 13:14:42 CST 2020
     */
    private Integer grade;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stu_grade.id
     *
     * @return the value of stu_grade.id
     *
     * @mbg.generated Wed Aug 05 13:14:42 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stu_grade.id
     *
     * @param id the value for stu_grade.id
     *
     * @mbg.generated Wed Aug 05 13:14:42 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stu_grade.name
     *
     * @return the value of stu_grade.name
     *
     * @mbg.generated Wed Aug 05 13:14:42 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stu_grade.name
     *
     * @param name the value for stu_grade.name
     *
     * @mbg.generated Wed Aug 05 13:14:42 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stu_grade.chinese
     *
     * @return the value of stu_grade.chinese
     *
     * @mbg.generated Wed Aug 05 13:14:42 CST 2020
     */
    public Integer getChinese() {
        return chinese;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stu_grade.chinese
     *
     * @param chinese the value for stu_grade.chinese
     *
     * @mbg.generated Wed Aug 05 13:14:42 CST 2020
     */
    public void setChinese(Integer chinese) {
        this.chinese = chinese;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stu_grade.math
     *
     * @return the value of stu_grade.math
     *
     * @mbg.generated Wed Aug 05 13:14:42 CST 2020
     */
    public Integer getMath() {
        return math;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stu_grade.math
     *
     * @param math the value for stu_grade.math
     *
     * @mbg.generated Wed Aug 05 13:14:42 CST 2020
     */
    public void setMath(Integer math) {
        this.math = math;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stu_grade.english
     *
     * @return the value of stu_grade.english
     *
     * @mbg.generated Wed Aug 05 13:14:42 CST 2020
     */
    public Integer getEnglish() {
        return english;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stu_grade.english
     *
     * @param english the value for stu_grade.english
     *
     * @mbg.generated Wed Aug 05 13:14:42 CST 2020
     */
    public void setEnglish(Integer english) {
        this.english = english;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stu_grade.grade
     *
     * @return the value of stu_grade.grade
     *
     * @mbg.generated Wed Aug 05 13:14:42 CST 2020
     */
    public Integer getGrade() {
        return grade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stu_grade.grade
     *
     * @param grade the value for stu_grade.grade
     *
     * @mbg.generated Wed Aug 05 13:14:42 CST 2020
     */
    public void setGrade(Integer grade) {
        this.grade = grade;
    }
}