package com.train.info.pojo;

import java.util.Date;

public class StudentInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stu_info.id
     *
     * @mbg.generated Wed Aug 05 13:14:42 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stu_info.name
     *
     * @mbg.generated Wed Aug 05 13:14:42 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stu_info.age
     *
     * @mbg.generated Wed Aug 05 13:14:42 CST 2020
     */
    private Integer age;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stu_info.birthday
     *
     * @mbg.generated Wed Aug 05 13:14:42 CST 2020
     */
    private Date birthday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stu_info.email
     *
     * @mbg.generated Wed Aug 05 13:14:42 CST 2020
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stu_info.country
     *
     * @mbg.generated Wed Aug 05 13:14:42 CST 2020
     */
    private String country;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stu_info.id
     *
     * @return the value of stu_info.id
     *
     * @mbg.generated Wed Aug 05 13:14:42 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stu_info.id
     *
     * @param id the value for stu_info.id
     *
     * @mbg.generated Wed Aug 05 13:14:42 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stu_info.name
     *
     * @return the value of stu_info.name
     *
     * @mbg.generated Wed Aug 05 13:14:42 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stu_info.name
     *
     * @param name the value for stu_info.name
     *
     * @mbg.generated Wed Aug 05 13:14:42 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stu_info.age
     *
     * @return the value of stu_info.age
     *
     * @mbg.generated Wed Aug 05 13:14:42 CST 2020
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stu_info.age
     *
     * @param age the value for stu_info.age
     *
     * @mbg.generated Wed Aug 05 13:14:42 CST 2020
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stu_info.birthday
     *
     * @return the value of stu_info.birthday
     *
     * @mbg.generated Wed Aug 05 13:14:42 CST 2020
     */
    public Date getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stu_info.birthday
     *
     * @param birthday the value for stu_info.birthday
     *
     * @mbg.generated Wed Aug 05 13:14:42 CST 2020
     */
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stu_info.email
     *
     * @return the value of stu_info.email
     *
     * @mbg.generated Wed Aug 05 13:14:42 CST 2020
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stu_info.email
     *
     * @param email the value for stu_info.email
     *
     * @mbg.generated Wed Aug 05 13:14:42 CST 2020
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stu_info.country
     *
     * @return the value of stu_info.country
     *
     * @mbg.generated Wed Aug 05 13:14:42 CST 2020
     */
    public String getCountry() {
        return country;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stu_info.country
     *
     * @param country the value for stu_info.country
     *
     * @mbg.generated Wed Aug 05 13:14:42 CST 2020
     */
    public void setCountry(String country) {
        this.country = country == null ? null : country.trim();
    }
}